project:
  type: website
  output-dir: .

website:
  title: "Saurabh Parate"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css