project:
  type: website
  output-dir: .

website:
  title: "Saurabh Parate"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: digital-marketing.qmd
            text: Digital Marketing
          - href: marketing-analytics.qmd
            text: Marketing Analytics
      - href: resume.qmd
        text: Resume
      - text: Analytics
        menu:
          - href: website-analytics.html
            text: Website Traffic
      - href: presentation.qmd
        text: Presentation

  page-footer:
    background: dark
    left: "© 2025 Saurabh Parate"
    center: "Built with [Quarto](https://quarto.org)"
    right:
      - icon: envelope
        href: mailto:contact@saurabhp.com
      - icon: linkedin
        href: https://linkedin.com/in/saurabh-parate
      - icon: globe
        href: https://saurabhp.com

format:
  html:
    theme:
      light: darkly
      dark: flatly
    css: styles.css
    include-in-header: ga.html